[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
Kaleido_jll = "f7e6163d-2fa5-5f23-b69c-1db539e41963"
Luxor = "ae8d54c2-7ccd-5906-9d76-62fc9837b5bc"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
